package com.chatRobot.dao;

import com.chatRobot.model.Historyorder;
import com.chatRobot.model.HistoryorderKey;

public interface HistoryorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historyorder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(HistoryorderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historyorder
     *
     * @mbggenerated
     */
    int insert(Historyorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historyorder
     *
     * @mbggenerated
     */
    int insertSelective(Historyorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historyorder
     *
     * @mbggenerated
     */
    Historyorder selectByPrimaryKey(HistoryorderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historyorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Historyorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table historyorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Historyorder record);
}