package com.chatRobot.dao;

import com.chatRobot.model.Tbautho;

public interface TbauthoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbautho
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String useraccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbautho
     *
     * @mbggenerated
     */
    int insert(Tbautho record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbautho
     *
     * @mbggenerated
     */
    int insertSelective(Tbautho record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbautho
     *
     * @mbggenerated
     */
    Tbautho selectByPrimaryKey(String useraccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbautho
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tbautho record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbautho
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tbautho record);
}