package com.chatRobot.model;

public class HistoryorderKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.historyorderId
     *
     * @mbggenerated
     */
    private String historyorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.historyproductId
     *
     * @mbggenerated
     */
    private String historyproductid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.historyorderId
     *
     * @return the value of historyorder.historyorderId
     *
     * @mbggenerated
     */
    public String getHistoryorderid() {
        return historyorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.historyorderId
     *
     * @param historyorderid the value for historyorder.historyorderId
     *
     * @mbggenerated
     */
    public void setHistoryorderid(String historyorderid) {
        this.historyorderid = historyorderid == null ? null : historyorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.historyproductId
     *
     * @return the value of historyorder.historyproductId
     *
     * @mbggenerated
     */
    public String getHistoryproductid() {
        return historyproductid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.historyproductId
     *
     * @param historyproductid the value for historyorder.historyproductId
     *
     * @mbggenerated
     */
    public void setHistoryproductid(String historyproductid) {
        this.historyproductid = historyproductid == null ? null : historyproductid.trim();
    }
}