package com.chatRobot.model;

import java.util.Date;

public class Historyorder extends HistoryorderKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.ordertime
     *
     * @mbggenerated
     */
    private Date ordertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.productname
     *
     * @mbggenerated
     */
    private String productname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.estimated
     *
     * @mbggenerated
     */
    private String estimated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.finishtime
     *
     * @mbggenerated
     */
    private Date finishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.channel
     *
     * @mbggenerated
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.weixin
     *
     * @mbggenerated
     */
    private String weixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.refunds
     *
     * @mbggenerated
     */
    private String refunds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.issubmit
     *
     * @mbggenerated
     */
    private String issubmit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.submittime
     *
     * @mbggenerated
     */
    private Date submittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.useraccount
     *
     * @mbggenerated
     */
    private String useraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.entertime
     *
     * @mbggenerated
     */
    private String entertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column historyorder.picture
     *
     * @mbggenerated
     */
    private String picture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.ordertime
     *
     * @return the value of historyorder.ordertime
     *
     * @mbggenerated
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.ordertime
     *
     * @param ordertime the value for historyorder.ordertime
     *
     * @mbggenerated
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.productname
     *
     * @return the value of historyorder.productname
     *
     * @mbggenerated
     */
    public String getProductname() {
        return productname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.productname
     *
     * @param productname the value for historyorder.productname
     *
     * @mbggenerated
     */
    public void setProductname(String productname) {
        this.productname = productname == null ? null : productname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.estimated
     *
     * @return the value of historyorder.estimated
     *
     * @mbggenerated
     */
    public String getEstimated() {
        return estimated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.estimated
     *
     * @param estimated the value for historyorder.estimated
     *
     * @mbggenerated
     */
    public void setEstimated(String estimated) {
        this.estimated = estimated == null ? null : estimated.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.state
     *
     * @return the value of historyorder.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.state
     *
     * @param state the value for historyorder.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.finishtime
     *
     * @return the value of historyorder.finishtime
     *
     * @mbggenerated
     */
    public Date getFinishtime() {
        return finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.finishtime
     *
     * @param finishtime the value for historyorder.finishtime
     *
     * @mbggenerated
     */
    public void setFinishtime(Date finishtime) {
        this.finishtime = finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.channel
     *
     * @return the value of historyorder.channel
     *
     * @mbggenerated
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.channel
     *
     * @param channel the value for historyorder.channel
     *
     * @mbggenerated
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.weixin
     *
     * @return the value of historyorder.weixin
     *
     * @mbggenerated
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.weixin
     *
     * @param weixin the value for historyorder.weixin
     *
     * @mbggenerated
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.refunds
     *
     * @return the value of historyorder.refunds
     *
     * @mbggenerated
     */
    public String getRefunds() {
        return refunds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.refunds
     *
     * @param refunds the value for historyorder.refunds
     *
     * @mbggenerated
     */
    public void setRefunds(String refunds) {
        this.refunds = refunds == null ? null : refunds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.issubmit
     *
     * @return the value of historyorder.issubmit
     *
     * @mbggenerated
     */
    public String getIssubmit() {
        return issubmit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.issubmit
     *
     * @param issubmit the value for historyorder.issubmit
     *
     * @mbggenerated
     */
    public void setIssubmit(String issubmit) {
        this.issubmit = issubmit == null ? null : issubmit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.submittime
     *
     * @return the value of historyorder.submittime
     *
     * @mbggenerated
     */
    public Date getSubmittime() {
        return submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.submittime
     *
     * @param submittime the value for historyorder.submittime
     *
     * @mbggenerated
     */
    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.useraccount
     *
     * @return the value of historyorder.useraccount
     *
     * @mbggenerated
     */
    public String getUseraccount() {
        return useraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.useraccount
     *
     * @param useraccount the value for historyorder.useraccount
     *
     * @mbggenerated
     */
    public void setUseraccount(String useraccount) {
        this.useraccount = useraccount == null ? null : useraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.entertime
     *
     * @return the value of historyorder.entertime
     *
     * @mbggenerated
     */
    public String getEntertime() {
        return entertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.entertime
     *
     * @param entertime the value for historyorder.entertime
     *
     * @mbggenerated
     */
    public void setEntertime(String entertime) {
        this.entertime = entertime == null ? null : entertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column historyorder.picture
     *
     * @return the value of historyorder.picture
     *
     * @mbggenerated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column historyorder.picture
     *
     * @param picture the value for historyorder.picture
     *
     * @mbggenerated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }
}