package com.chatRobot.model;

public class Jdautho {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.useraccount
     *
     * @mbggenerated
     */
    private String useraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.jdappkey
     *
     * @mbggenerated
     */
    private String jdappkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.jdappsecret
     *
     * @mbggenerated
     */
    private String jdappsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.jdaccesstoken
     *
     * @mbggenerated
     */
    private String jdaccesstoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.jdunionid
     *
     * @mbggenerated
     */
    private String jdunionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.useraccount
     *
     * @return the value of jdautho.useraccount
     *
     * @mbggenerated
     */
    public String getUseraccount() {
        return useraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.useraccount
     *
     * @param useraccount the value for jdautho.useraccount
     *
     * @mbggenerated
     */
    public void setUseraccount(String useraccount) {
        this.useraccount = useraccount == null ? null : useraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.jdappkey
     *
     * @return the value of jdautho.jdappkey
     *
     * @mbggenerated
     */
    public String getJdappkey() {
        return jdappkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.jdappkey
     *
     * @param jdappkey the value for jdautho.jdappkey
     *
     * @mbggenerated
     */
    public void setJdappkey(String jdappkey) {
        this.jdappkey = jdappkey == null ? null : jdappkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.jdappsecret
     *
     * @return the value of jdautho.jdappsecret
     *
     * @mbggenerated
     */
    public String getJdappsecret() {
        return jdappsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.jdappsecret
     *
     * @param jdappsecret the value for jdautho.jdappsecret
     *
     * @mbggenerated
     */
    public void setJdappsecret(String jdappsecret) {
        this.jdappsecret = jdappsecret == null ? null : jdappsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.jdaccesstoken
     *
     * @return the value of jdautho.jdaccesstoken
     *
     * @mbggenerated
     */
    public String getJdaccesstoken() {
        return jdaccesstoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.jdaccesstoken
     *
     * @param jdaccesstoken the value for jdautho.jdaccesstoken
     *
     * @mbggenerated
     */
    public void setJdaccesstoken(String jdaccesstoken) {
        this.jdaccesstoken = jdaccesstoken == null ? null : jdaccesstoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.jdunionid
     *
     * @return the value of jdautho.jdunionid
     *
     * @mbggenerated
     */
    public String getJdunionid() {
        return jdunionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.jdunionid
     *
     * @param jdunionid the value for jdautho.jdunionid
     *
     * @mbggenerated
     */
    public void setJdunionid(String jdunionid) {
        this.jdunionid = jdunionid == null ? null : jdunionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.phone
     *
     * @return the value of jdautho.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.phone
     *
     * @param phone the value for jdautho.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.name
     *
     * @return the value of jdautho.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.name
     *
     * @param name the value for jdautho.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}