package com.chatRobot.model;

public class Jdautho {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.user_account
     *
     * @mbggenerated
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.Jd_appKey
     *
     * @mbggenerated
     */
    private String jdAppkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.Jd_appSecret
     *
     * @mbggenerated
     */
    private String jdAppsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.Jd_Access_token
     *
     * @mbggenerated
     */
    private String jdAccessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.jdunionid
     *
     * @mbggenerated
     */
    private String jdunionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jdautho.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.user_account
     *
     * @return the value of jdautho.user_account
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.user_account
     *
     * @param userAccount the value for jdautho.user_account
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.Jd_appKey
     *
     * @return the value of jdautho.Jd_appKey
     *
     * @mbggenerated
     */
    public String getJdAppkey() {
        return jdAppkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.Jd_appKey
     *
     * @param jdAppkey the value for jdautho.Jd_appKey
     *
     * @mbggenerated
     */
    public void setJdAppkey(String jdAppkey) {
        this.jdAppkey = jdAppkey == null ? null : jdAppkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.Jd_appSecret
     *
     * @return the value of jdautho.Jd_appSecret
     *
     * @mbggenerated
     */
    public String getJdAppsecret() {
        return jdAppsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.Jd_appSecret
     *
     * @param jdAppsecret the value for jdautho.Jd_appSecret
     *
     * @mbggenerated
     */
    public void setJdAppsecret(String jdAppsecret) {
        this.jdAppsecret = jdAppsecret == null ? null : jdAppsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.Jd_Access_token
     *
     * @return the value of jdautho.Jd_Access_token
     *
     * @mbggenerated
     */
    public String getJdAccessToken() {
        return jdAccessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.Jd_Access_token
     *
     * @param jdAccessToken the value for jdautho.Jd_Access_token
     *
     * @mbggenerated
     */
    public void setJdAccessToken(String jdAccessToken) {
        this.jdAccessToken = jdAccessToken == null ? null : jdAccessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.jdunionid
     *
     * @return the value of jdautho.jdunionid
     *
     * @mbggenerated
     */
    public String getJdunionid() {
        return jdunionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.jdunionid
     *
     * @param jdunionid the value for jdautho.jdunionid
     *
     * @mbggenerated
     */
    public void setJdunionid(String jdunionid) {
        this.jdunionid = jdunionid == null ? null : jdunionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.phone
     *
     * @return the value of jdautho.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.phone
     *
     * @param phone the value for jdautho.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jdautho.name
     *
     * @return the value of jdautho.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jdautho.name
     *
     * @param name the value for jdautho.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}