package com.chatRobot.model;

public class Pddautho {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.user_account
     *
     * @mbggenerated
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.pdd_client_id
     *
     * @mbggenerated
     */
    private String pddClientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.pdd_client_secret
     *
     * @mbggenerated
     */
    private String pddClientSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.ddk_id
     *
     * @mbggenerated
     */
    private String ddkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.user_account
     *
     * @return the value of pddautho.user_account
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.user_account
     *
     * @param userAccount the value for pddautho.user_account
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.pdd_client_id
     *
     * @return the value of pddautho.pdd_client_id
     *
     * @mbggenerated
     */
    public String getPddClientId() {
        return pddClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.pdd_client_id
     *
     * @param pddClientId the value for pddautho.pdd_client_id
     *
     * @mbggenerated
     */
    public void setPddClientId(String pddClientId) {
        this.pddClientId = pddClientId == null ? null : pddClientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.pdd_client_secret
     *
     * @return the value of pddautho.pdd_client_secret
     *
     * @mbggenerated
     */
    public String getPddClientSecret() {
        return pddClientSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.pdd_client_secret
     *
     * @param pddClientSecret the value for pddautho.pdd_client_secret
     *
     * @mbggenerated
     */
    public void setPddClientSecret(String pddClientSecret) {
        this.pddClientSecret = pddClientSecret == null ? null : pddClientSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.ddk_id
     *
     * @return the value of pddautho.ddk_id
     *
     * @mbggenerated
     */
    public String getDdkId() {
        return ddkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.ddk_id
     *
     * @param ddkId the value for pddautho.ddk_id
     *
     * @mbggenerated
     */
    public void setDdkId(String ddkId) {
        this.ddkId = ddkId == null ? null : ddkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.phone
     *
     * @return the value of pddautho.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.phone
     *
     * @param phone the value for pddautho.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.name
     *
     * @return the value of pddautho.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.name
     *
     * @param name the value for pddautho.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}