package com.chatRobot.model;

public class Pddautho {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.useraccount
     *
     * @mbggenerated
     */
    private String useraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.pddclientid
     *
     * @mbggenerated
     */
    private String pddclientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.pddclientsecret
     *
     * @mbggenerated
     */
    private String pddclientsecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.ddkid
     *
     * @mbggenerated
     */
    private String ddkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pddautho.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.useraccount
     *
     * @return the value of pddautho.useraccount
     *
     * @mbggenerated
     */
    public String getUseraccount() {
        return useraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.useraccount
     *
     * @param useraccount the value for pddautho.useraccount
     *
     * @mbggenerated
     */
    public void setUseraccount(String useraccount) {
        this.useraccount = useraccount == null ? null : useraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.pddclientid
     *
     * @return the value of pddautho.pddclientid
     *
     * @mbggenerated
     */
    public String getPddclientid() {
        return pddclientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.pddclientid
     *
     * @param pddclientid the value for pddautho.pddclientid
     *
     * @mbggenerated
     */
    public void setPddclientid(String pddclientid) {
        this.pddclientid = pddclientid == null ? null : pddclientid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.pddclientsecret
     *
     * @return the value of pddautho.pddclientsecret
     *
     * @mbggenerated
     */
    public String getPddclientsecret() {
        return pddclientsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.pddclientsecret
     *
     * @param pddclientsecret the value for pddautho.pddclientsecret
     *
     * @mbggenerated
     */
    public void setPddclientsecret(String pddclientsecret) {
        this.pddclientsecret = pddclientsecret == null ? null : pddclientsecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.ddkid
     *
     * @return the value of pddautho.ddkid
     *
     * @mbggenerated
     */
    public String getDdkid() {
        return ddkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.ddkid
     *
     * @param ddkid the value for pddautho.ddkid
     *
     * @mbggenerated
     */
    public void setDdkid(String ddkid) {
        this.ddkid = ddkid == null ? null : ddkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.phone
     *
     * @return the value of pddautho.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.phone
     *
     * @param phone the value for pddautho.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pddautho.name
     *
     * @return the value of pddautho.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pddautho.name
     *
     * @param name the value for pddautho.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}