package com.chatRobot.model;

public class Tbautho {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.user_account
     *
     * @mbggenerated
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.taobao_session
     *
     * @mbggenerated
     */
    private String taobaoSession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.taobao_account
     *
     * @mbggenerated
     */
    private String taobaoAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.user_account
     *
     * @return the value of tbautho.user_account
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.user_account
     *
     * @param userAccount the value for tbautho.user_account
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.taobao_session
     *
     * @return the value of tbautho.taobao_session
     *
     * @mbggenerated
     */
    public String getTaobaoSession() {
        return taobaoSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.taobao_session
     *
     * @param taobaoSession the value for tbautho.taobao_session
     *
     * @mbggenerated
     */
    public void setTaobaoSession(String taobaoSession) {
        this.taobaoSession = taobaoSession == null ? null : taobaoSession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.taobao_account
     *
     * @return the value of tbautho.taobao_account
     *
     * @mbggenerated
     */
    public String getTaobaoAccount() {
        return taobaoAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.taobao_account
     *
     * @param taobaoAccount the value for tbautho.taobao_account
     *
     * @mbggenerated
     */
    public void setTaobaoAccount(String taobaoAccount) {
        this.taobaoAccount = taobaoAccount == null ? null : taobaoAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.phone
     *
     * @return the value of tbautho.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.phone
     *
     * @param phone the value for tbautho.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.name
     *
     * @return the value of tbautho.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.name
     *
     * @param name the value for tbautho.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}