package com.chatRobot.model;

public class Tbautho {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.useraccount
     *
     * @mbggenerated
     */
    private String useraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.taobaosession
     *
     * @mbggenerated
     */
    private String taobaosession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.taobaoaccount
     *
     * @mbggenerated
     */
    private String taobaoaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbautho.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.id
     *
     * @return the value of tbautho.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.id
     *
     * @param id the value for tbautho.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.useraccount
     *
     * @return the value of tbautho.useraccount
     *
     * @mbggenerated
     */
    public String getUseraccount() {
        return useraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.useraccount
     *
     * @param useraccount the value for tbautho.useraccount
     *
     * @mbggenerated
     */
    public void setUseraccount(String useraccount) {
        this.useraccount = useraccount == null ? null : useraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.taobaosession
     *
     * @return the value of tbautho.taobaosession
     *
     * @mbggenerated
     */
    public String getTaobaosession() {
        return taobaosession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.taobaosession
     *
     * @param taobaosession the value for tbautho.taobaosession
     *
     * @mbggenerated
     */
    public void setTaobaosession(String taobaosession) {
        this.taobaosession = taobaosession == null ? null : taobaosession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.taobaoaccount
     *
     * @return the value of tbautho.taobaoaccount
     *
     * @mbggenerated
     */
    public String getTaobaoaccount() {
        return taobaoaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.taobaoaccount
     *
     * @param taobaoaccount the value for tbautho.taobaoaccount
     *
     * @mbggenerated
     */
    public void setTaobaoaccount(String taobaoaccount) {
        this.taobaoaccount = taobaoaccount == null ? null : taobaoaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.phone
     *
     * @return the value of tbautho.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.phone
     *
     * @param phone the value for tbautho.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbautho.name
     *
     * @return the value of tbautho.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbautho.name
     *
     * @param name the value for tbautho.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}